#!/bin/python3

import subprocess
import re
import json
import argparse

parser = argparse.ArgumentParser(description="Move to another keyboard layout.")
parser.add_argument(
    "steps",
    type=int,
    nargs="?",
    help="Number of steps to take (default +1).",
    default=1,
)


def gnome_shell_eval(script):
    cmd = (
        "gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell "
        "--method org.gnome.Shell.Eval "
        f'"{script}"'
    )
    error_code, output = subprocess.getstatusoutput(cmd)
    assert error_code == 0, (error_code, output)
    m = re.match(f"\(true, '([^']*)'\)", output)
    assert m, m
    json_data = m.group(1)
    if len(json_data) == 0:
        return None
    return json.loads(json_data)


def main():
    args = parser.parse_args()
    n_layouts = len(
        gnome_shell_eval(
            "imports.ui.status.keyboard.getInputSourceManager().inputSources"
        )
    )
    current_idx = gnome_shell_eval(
        "imports.ui.status.keyboard.getInputSourceManager().currentSource"
    )["index"]
    next_idx = (current_idx + args.steps) % n_layouts
    gnome_shell_eval(
        "imports.ui.status.keyboard.getInputSourceManager()"
        f".inputSources[{next_idx}].activate()"
    )


if __name__ == "__main__":
    main()
